CUDA_VISIBLE_DEVICES=6 python main.py \
  data.target_shift=12 \
  data.ts_test=73 \
  data.target_mask_mode=observed_only \
  data.feat_norm=norm1 \
  data.num_hops=2 \
  data.window_size=12 \
  data.rp_dim=32 \
  training.batch_size=64 \
  training.epochs=100 \
  training.eval_interval=1 \
  training.predict_last=false \
  training.run_name_sufix=lr_wd \
  model.hidden_dim=64 \
  model.mlp_layers=2 \
  model.num_layers=2 \
  model.num_heads=4 \
  model.dropout=0.3 \
  model.conv_filters=2 \
  model.merge_mode=mean \
  optimizer.learning_rate=1e-3 \
  optimizer.weight_decay=0.1 \
  logging.wandb_project="pgim-rphgnn-shift12-tune"

CUDA_VISIBLE_DEVICES=6 python main.py \
  data.target_shift=12 \
  data.ts_test=73 \
  data.target_mask_mode=observed_only \
  data.feat_norm=norm1 \
  data.num_hops=2 \
  data.window_size=12 \
  data.rp_dim=32 \
  training.batch_size=64 \
  training.epochs=100 \
  training.eval_interval=1 \
  training.predict_last=false \
  training.run_name_sufix=lr_wd \
  model.hidden_dim=64 \
  model.mlp_layers=2 \
  model.num_layers=2 \
  model.num_heads=4 \
  model.dropout=0.3 \
  model.conv_filters=2 \
  model.merge_mode=mean \
  optimizer.learning_rate=1e-3 \
  optimizer.weight_decay=0.2 \
  logging.wandb_project="pgim-rphgnn-shift12-tune"